"""Structured scientific tools."""

from .analysis import (
    CellAnnotationEvaluationToolResult,
    CellClusteringEvaluationToolResult,
    CellClusteringToolResult,
    CellNeighborsToolResult,
    CellLabelTransferToolResult,
    CellUMAPToolResult,
    EpiZooEmbeddingToolResult,
    ReplicatePseudobulkToolResult,
    ReplicateDifferentialAccessibilityToolResult,
    ScATACFeatureSpaceToolResult,
    build_cell_neighbors,
    cluster_cells,
    compute_cell_umap,
    epizoo_embed_cells,
    evaluate_cell_annotation,
    evaluate_cell_clustering,
    transfer_cell_labels,
    build_replicate_pseudobulk,
    run_replicate_differential_accessibility,
    validate_scATAC_feature_space,
)
from .data import ScATACInspection, inspect_scATAC

__all__ = [
    "CellAnnotationEvaluationToolResult",
    "CellClusteringEvaluationToolResult",
    "CellClusteringToolResult",
    "CellNeighborsToolResult",
    "CellLabelTransferToolResult",
    "CellUMAPToolResult",
    "EpiZooEmbeddingToolResult",
    "ReplicatePseudobulkToolResult",
    "ReplicateDifferentialAccessibilityToolResult",
    "ScATACFeatureSpaceToolResult",
    "ScATACInspection",
    "build_cell_neighbors",
    "cluster_cells",
    "compute_cell_umap",
    "epizoo_embed_cells",
    "evaluate_cell_annotation",
    "evaluate_cell_clustering",
    "inspect_scATAC",
    "transfer_cell_labels",
    "build_replicate_pseudobulk",
    "run_replicate_differential_accessibility",
    "validate_scATAC_feature_space",
]
