"""Verified result boundaries for deterministic scientific reporting."""

from .analysis_report import (
    ANALYSIS_REPORT_ARTIFACT_TYPE,
    ANALYSIS_REPORT_BUNDLE_DIRNAME,
    ANALYSIS_REPORT_FILENAME,
    ANALYSIS_REPORT_MANIFEST_FILENAME,
    ANALYSIS_REPORT_SCHEMA_VERSION,
    REPORT_SPEC_VERSION,
    AnalysisReportError,
    AnalysisReportResult,
    ReportFactRecord,
    ReportFigureResult,
    build_analysis_report,
    verify_analysis_report,
)

from .evidence import (
    ANALYSIS_EVIDENCE_ARTIFACT_TYPE,
    ANALYSIS_EVIDENCE_FILENAME,
    ANALYSIS_EVIDENCE_SCHEMA_VERSION,
    AnalysisEvidenceError,
    AnalysisEvidenceResult,
    build_analysis_evidence,
    verify_analysis_evidence,
)
from .visualization import (
    ANALYSIS_VISUALIZATION_ARTIFACT_TYPE,
    ANALYSIS_VISUALIZATION_BUNDLE_DIRNAME,
    ANALYSIS_VISUALIZATION_MANIFEST_FILENAME,
    ANALYSIS_VISUALIZATION_SCHEMA_VERSION,
    PLOTTING_SPEC_VERSION,
    AnalysisVisualizationError,
    AnalysisVisualizationResult,
    VisualizationFigureResult,
    build_analysis_visualizations,
    verify_analysis_visualizations,
)

__all__ = [
    "ANALYSIS_REPORT_ARTIFACT_TYPE",
    "ANALYSIS_REPORT_BUNDLE_DIRNAME",
    "ANALYSIS_REPORT_FILENAME",
    "ANALYSIS_REPORT_MANIFEST_FILENAME",
    "ANALYSIS_REPORT_SCHEMA_VERSION",
    "REPORT_SPEC_VERSION",
    "AnalysisReportError",
    "AnalysisReportResult",
    "ReportFactRecord",
    "ReportFigureResult",
    "build_analysis_report",
    "verify_analysis_report",
    "ANALYSIS_EVIDENCE_ARTIFACT_TYPE",
    "ANALYSIS_EVIDENCE_FILENAME",
    "ANALYSIS_EVIDENCE_SCHEMA_VERSION",
    "AnalysisEvidenceError",
    "AnalysisEvidenceResult",
    "build_analysis_evidence",
    "verify_analysis_evidence",
    "ANALYSIS_VISUALIZATION_ARTIFACT_TYPE",
    "ANALYSIS_VISUALIZATION_BUNDLE_DIRNAME",
    "ANALYSIS_VISUALIZATION_MANIFEST_FILENAME",
    "ANALYSIS_VISUALIZATION_SCHEMA_VERSION",
    "PLOTTING_SPEC_VERSION",
    "AnalysisVisualizationError",
    "AnalysisVisualizationResult",
    "VisualizationFigureResult",
    "build_analysis_visualizations",
    "verify_analysis_visualizations",
]
